import {useCallback, useMemo, useState} from "react";
import type {EditorConfig} from "../logic/editorTypes.ts";
import {ALL_EDITORS} from "../logic/editorConfigs.ts";
import { designGuidesAroundMutation, type Guide } from '../logic/guides.ts';
import {ALL_EDIT_REQUESTS, type EditRequestConfig} from "../logic/mutation.ts";
import { fasta } from "bioinformatics-parser";

interface DesignerProps {
  onAnalyseComplete?: () => void; // Optional callback to reset state
}

export function useBaseEditorDesigner ({onAnalyseComplete}: DesignerProps = {}) {
    // const [DNASequence, setDNASequence] = useState<string>("CTTTATATATCTTGTGGAAAGGACGAAACACCCACCTAGGGAGAAGGGGAGCATGTTTTAGTACTCTGTAATGAAAATTACAGAATCTACTAAAACAAGGCAAAATGCCGTGTTTATCTCGTCAACTTGTTGGCGAGATTTTTTTAAGCTTGGGCCGCTCGAGCCATAGAGCCCACCGCATCCCCAGCATGCCTGCTATTGTCTTCCCAATCCTCCCCCTTGCTGTCCTGCCCCACCCCACCCCCCAGAATAGAATGACACCTACTCAGACAATGCGATGCAATTTCCTCATTTTATTAGGAAAGGACAGTGGGAGTGGCACCTTCCAGGGTCAAGGAAGGCACGGGGGAGGGGCAAACAACAGATGGCTGGCAACTAGAAGGCACAGTCGAGATCTATTAGACTTTCCTCTTCTTCTTGGGCTCGAATTCGCTGCCGTCGGCGGTTCTTTTTGAGCCGCCAGAGCCTTTCTTGATAATCTGAGGATGTTTCTTGCTCTTGACTTCATACAGGTTCCCCAGGATGTCTGTGCTGTACTTCTTGATGCTCTGTGTCTTAGAGGCGATGGTCTTGATGATGCGAGGGGGCCTCTTATCATTCATGTTCTCCAGATACTCCCTGTAGGTGATGTCGATCATATTCACTTCGATTCTGTTCAGCAGATCATTGTTCACGCCGATCACTCTATACAGCTCGCCATTGATCTTGATCAGGTCATTGTTGTAAAAAGAGGCGATGAACTCGGCCTGGTTGCTGATCTTCTTCAGCTTCTTGGCCTCCTCGTAGCACTTGCTGTTCACCTCATAGTAGTTCTCCTTCTTGATCACATCCAGATTCTTCACTGTCACAAACTTATACACGCCGTTGTCCAGGTACACGTCGAACCGGTATGGCTTCAGGCTCAGCTTCACCACCTTATTGCGAGAGTTAGGGTAATCGTCGGTGATGTCCAGGTGGGCATTCAGCTTGTTGCCATAGTACTTGATCTTCTTGATCACGGGGCCATTATCCTTCTTGCTATACTTTGTCAGGTAGTTGCCTGTCTCCTCATAGTACTTATACAGTGGGTTCTTCTCGTCGCCGTACTGCTCCATGATCAGCTTCAGCTTCTGATATGTCTGAGGATCGTGGTGGTACATCAGCAGCTTCTCGGGAGACTTGTTGATCAGCTTCTTCAGCTTGTCATTATCCTTGTCGTACAGGCCGTTCAGATTGTTCACGATCAGGGTATTGCCCTTATCGTCCTTCCGTGTGCTATACAGGGTGTCATTGATCAGCTCGCGGTTGGGCTTCTTATCCACCCTGTGAGAATACTTGTAGTCCTTGAAGTCCTTGATGTGCTTGATCTGGTGAGGTGTGATGAAAATCTCCTTGTACTCCTGCTCTGTCTCGATCTCGGGCATGCTCTCGGCCTGCTTCTCCTCGAACATCTGGTTCTCCATCACTTTCTTGGCCTTGTCCAGCTTCTTCCACTCCTTAAAGATGAAGTCGGCATTGGCGATGATCAGGGCATCCTCGGCGTGGTGCTTATAGCCCTTGTTGCGCTCCTTCTTAAACTTCCACTTTCTCCGCAGAAAGGAGGTGAAGCCGCCGTTGATGCTCTTCACCTTCACATCCAGATTGTTCACTCTGAAATAAGACCGCAGCAGATTCATCAGGCCGCGTGTGGCGTATCTGGTGTCCACCAGATTCCGGTTGATGAAGTCCTTCTGCACGGAGAATCTGTTGATGTCCCGCTCCTCCAGCAGGTACTCCTTCTTGGTCTTGCTGATGCGGCCCTTGCCCTTGGCCAGATTCAGGATGTGCTTCTTGAATGTCTCGTAGCTGATCTTAGAATCGGAGCTAGACAGGTACTGGAAAGGGGTCCTATTGCCCTTCTTGCTGTTCTCCTCCTGCTTCACCAGCACCTTATTGTTAAAAGAATTGTCGAAGCTCACGCTCCGGGGGATGATGTGATCCACCTCGTAGTTGAATGGATTGTTCAGCAGGTCCTCCAGAGGGATGGCCTCCAGAGAATACAGACACTTGCCCTCCTGCATATCGTGCAGCTTGATCTTCTCGATCAGGTACTTGGCGTTCTCCTTGCCTGTGGTTCTGATGATCTCCTCGATCCGCTCATTGGTCTGGCGGTTCCTCTTCTGCATCTCATTGATCATCTTCTGGGCGTCCTTGGAGTTCTTCTCCCTGGCCAGCTCGATGATGATATCATTGGGCAGGCCGTACTTCTTGATGATGGCGTTGATCACTTTGATGCTCTGGATGAAGCTCCGCTTCACCACGGGAGACAGGATGAAATCGTCCACCAGTGTGGTTGGGATCTCCTTCTGCTGGGACAGGTCCACCTTCTTTGGCACCAGCTTCAGCCGGTTAAAGATGGCGATCTGATTGTCGTTTGTGTGCCACAGCTCATCCAGGATCAGATTGATGGCCTTCAGGCTCAGGTTGTGTGTGCCGGTGTAGCCCTTCAGATTGCTGATCTGCTCGATCTCCTCCTGTGTCAGCTCGCTATTCAGGTTGGTCAGCTCCTCCTGGATGTCCTCGGAGCTCTGATAGATGGTCAGGATCTTGGCGATCTGATCCAGCAGCTCGGCGTTCTCGATGATCTCCTTCCGGGCTGTGATGTCCTTGATATCGTGATACACCTTCAGATTGGTGAACTCTGGCTTGCCTGTGGAGGTCACGCGGTAGCCCTTGATGTCCTCCTCGTTCACCAGGATCTCCTTGGCGATCTGCTTCAGTGTAGGCTTCTTCTTCTGCTTGAACACGTTCTCGATGATCTGGAACTTCTCATAGTACTCCAGCTTCTCGTTCTCATCCCTGGTGATGACCAGGTTGTTCAGGTCATTCAGGGCGTTGTACAGATCGGCGTTATAGGCGTACTTCACGCTTCTCAGCTCCTCTGGAAAATAGGTGCAGTGGCCCATCAGCATCTCGTACCACTCCTTGATGTCCTTCCAGCCGAAGGGAGAGCCCTCTCCTGGTCCCTCATAGTATGTGCGCCTTGTCTCCAGCAGGTCGATATATGTATCGATAAAGGACTGATCCAGCTGGTGGTAGGCCTTCTGCACCTTCAGCAGCTGCTTGGCCTCCTTCACGTAGTCAGAGGTCTTGAAGCGATTGATGGAGCCCCTCACCTCGCCATCCTTCTTCAGCCGCTCCAGCTGCAGCTCGGCCACATACTTCTCCTCCAGGGCCTTGGAATTGCGGCTGATCTGCTCCTTTGTGGACAGCTCGTTGCCGGTGTCCTCCTCCACCTCATTCACGTTGTGCACGCCTCTCCTCTTTGCCAGGTGCAGCAGGGCGGCGCTAAACTCCTCCTCAGACAGCTTCTGGGACAGGCCCTTCACTCTGGCCTCATAAGGATTGATGCCAGACAGCTCGGAGTGGTCGGTCAGCAGGTTGTAATCGAACAGCAGCTTCTTCACTCTCTGGATTCTGTGGCGCCTTCTCCGCTTCAGGCGCCTTGCTCCCCTCTTGGATCTCCGGCCCTCATTGTTCTCCACGTTGGCCTCCTTGAACAGTCTCACGCCGGCGTCGATCACGTCCCTTGTCTCGTAGTCAATGATGCCATAGCCCACTGATGTAATGCCAATGGCCAGCCCCAGAATGTAATTTCGCTTCCCTGACCCCCCGCTGCTGCCCCCGCTGCTTTCAGGTGTTGCGCTCTCGCTTGTGCCAGGTGTCTCAGAGCCAGAGGAGCCTCCGCTAGATCCTCCGGAGTTGATGGAGCTCTGGGCCTTCTTCTGAGCATTGAACACCTGTCTAGGCATCCGATAGAAATCGCACAGCAGGGCGGCACATTCATCTGCCAGGATTCCCTCGGTAATTTCGACGCGGTGATTCATGCCGGGGTAGTTCAGCACGTTCATCAGGGAGCCTGCGGCGCCTCTTTTTGAGTTCCTCACGCCAAACACCACGCGGCCGATCCTAGAGTGGATCATGGCGCCGGCGCACATCACGCAAGGCTCGAATGTCACGTACAGGGTGGCGTCAATCAGTCTGTAGTTCTGCATGACCAGGCCGCCCTGTCTCAGGGCCATAATTTCGGCATGGGCTGTTGGGTCGTGCAGGCCGATGGCTCTGTTCCAGCCCTCGCCGATCACTCTATTGTTCAGCACCAGCACGGCTCCCACAGGCACCTCCCTCTCATCCCGTGCCCTCTTGGCCAGGGTCAGGGCATGTCTCATCCAGTACTCGTGGGAAAACTCCACCTCAGAGACTTTCCGCTTCTTCTTTGGTGACTCGAACTCGCTTCCGTCGGCTGTCCGTTTCATGGTGGCACCGGTCCTGTGTTCTGGCGGCAAACCCGTTGCGAAAAAGAACGTTCACGGCGACTACTGCACTTATATACGGTTCTCCCCCACCCTCGGGAAAAAGGCGGAGCCAGTACACGACATCACTTTCCCAGTTTACCCCGCGCCACCTTCTCTAGGCACCGGATCAATTGCCGACCCCTCCCCCCAACTTCTCGGGGACTGTGGGCGATGTGCGCTCTGCCCACTGACGGGCACCGGAGCCAATTCCCACTCCTTTCAAGACCTAGCTAGCGAATTCTAGAGGCCGCAGGAACCCCTAGTGATGGAGTTGGCCACTCCCTCTCTGCGCGCTCGCTCGCTCACTGAGGCCGGGCGACCAAAGGTCGCCCGACGCCCGGGCTTTGCCCGGGCGGCCTCAGTGAGCGAGCGAGCGCGCAGCCTTAATTAAATCTGGCGTAATCATGGTCATAGCTGTTTCCTGTGTGAAATTGTTATCCGCTCACAATTCCACACAACATACGAGCCGGAAGCATAAAGTGTAAAGCCTGGGGTGCCTAATGAGTGAGCTAACTCACATTAATTGCGTTGCGCTCACTGCCCGCTTTCCAGTCGGGAAACCTGTCGTGCCAGCTGCATTAATGAATCGGCCAACGCGCGGGGAGAGGCGGTTTGCGTATTGGGCGCTCTTCCGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGCTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGACCCACGCTCACCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTAAATTGTAAGCGTTAATATTTTGTTAAAATTCGCGTTAAATTTTTGTTAAATCAGCTCATTTTTTAACCAATAGGCCGAAATCGGCAAAATCCCTTATAAATCAAAAGAATAGACCGAGATAGGGTTGAGTGTTGTTCCAGTTTGGAACAAGAGTCCACTATTAAAGAACGTGGACTCCAACGTCAAAGGGCGAAAAACCGTCTATCAGGGCGATGGCCCACTACGTGAACCATCACCCTAATCAAGTTTTTTGGGGTCGAGGTGCCGTAAAGCACTAAATCGGAACCCTAAAGGGAGCCCCCGATTTAGAGCTTGACGGGGAAAGCCGGCGAACGTGGCGAGAAAGGAAGGGAAGAAAGCGAAAGGAGCGGGCGCTAGGGCGCTGGCAAGTGTAGCGGTCACGCTGCGCGTAACCACCACACCCGCCGCGCTTAATGCGCCGCTACAGGGCGCGTCCCATTCGCCATTCAGGCTGCGCAACTGTTGGGAAGGGCGATCGGTGCGGGCCTCTTCGCTATTACGCCAGCTGGCGAAAGGGGGATGTGCTGCAAGGCGATTAAGTTGGGTAACGCCAGGGTTTTCCCAGTCACGACGTTGTAAAACGACGGCCAGTGAATTAGGTTAATTAAGGCTGCGCGCTCGCTCGCTCACTGAGGCCGCCCGGGCAAAGCCCGGGCGTCGGGCGACCTTTGGTCGCCCGGCCTCAGTGAGCGAGCGAGCGCGCAGAGAGGGAGTGGCCAACTCCATCACTAGGGGTTCCTGCGGCCGCAAGGTCGGGCAGGAAGAGGGCCTATTTCCCATGATTCCTTCATATTTGCATATACGATACAAGGCTGTTAGAGAGATAATTAGAATTAATTTGACTGTAAACACAAAGATATTAGTACAAAATACGTGACGTAGAAAGTAATAATTTCTTGGGTAGTTTGCAGTTTTAAAATTATGTTTTAAAATGGACTATCATATGCTTACCGTAACTTGAAAGTATTTCGATTTCTTGG");
    const [DNASequence, setDNASequence] = useState<string>("CCTTGTTTTTTATGTAATATGCCCCCTGGGGTCTGGCCCTTGG"); // SpCas9 and SaCas9 test ABE
    // const [DNASequence, setDNASequence] = useState<string>("CCTTGTTTTTTATGTAATATGCCCCCCCCCTGGCCCTTGG");
    const [error, setError] = useState<string>("");
    const [selectedEditorName, setSelectedEditorName] = useState<string>("auto");
    // const [selectedEditorName, setSelectedEditorName] = useState<string>("ABE8e (SpCas9)");
    const [desiredEdit, setDesiredEdit] = useState<"A_TO_G" | "C_TO_T">("A_TO_G");
    const [guides, setGuides] = useState<Guide[]>([]);
    // const [mutationPos, setMutationPos] = useState<number>(16);
    const [mutationPos, setMutationPos] = useState<number>(17);
    const [targetStrand, setTargetStrand] = useState<"+" | "-">("+");
    const [seqvizZoom, setSeqvizZoom] = useState<number>(11);
    const [seqvizSelectEnabled, setSeqvizSelectEnabled] = useState<boolean>(true);

    const editor: EditorConfig | string = useMemo(
        () => {
          if(selectedEditorName === "auto") return "auto";
          return ALL_EDITORS.find((e) => e.name === selectedEditorName)
        },
        [selectedEditorName]
    );

    const desiredEditObject: EditRequestConfig = useMemo(
        () => ALL_EDIT_REQUESTS.find((e) => e.name === desiredEdit ),
        [desiredEdit]
    );

    const analyse = useCallback(() => {
        // zero base conversion
        const absMutationPos: number = mutationPos - 1;
        const guides: Guide [] = designGuidesAroundMutation(
          DNASequence,
          absMutationPos,
          desiredEditObject,
          editor
        );
        setGuides(guides);

        console.log("Guides from useBaseEditorDesigner");
        console.log(guides);

      if (onAnalyseComplete) {
        onAnalyseComplete();
      }

    }, [editor, DNASequence, mutationPos, desiredEditObject, onAnalyseComplete]);


    const onFastaFileUpload = (e) =>  {
      const file = e.target.files[0];

      if (!file) return;

      let fileText: string | ArrayBuffer | null = null;

      const reader = new FileReader();
      reader.onload = (ev) => {
        fileText = ev.target?.result as string;

        // parse fasta into text
        const {error, result} = fasta.parse(fileText);

        if (error)
          console.log(error);

        // update the DNA sequence with the file contents
        setDNASequence(result[0].data ?? "");
      }

      reader.onerror = (ev) => {
        console.log('Error occurred while uploading file');

      }
      reader.readAsText(file);
    }

  return useMemo(() => ({
    DNASequence,
    setDNASequence,
    selectedEditorName,
    setSelectedEditorName,
    desiredEdit,
    setDesiredEdit,
    error,
    setError,
    analyse,
    mutationPos,
    setMutationPos,
    targetStrand,
    setTargetStrand,
    guides,
    seqvizZoom,
    setSeqvizZoom,
    onFastaFileUpload
  }), [
    DNASequence, selectedEditorName, desiredEdit, error,
    analyse, mutationPos, targetStrand, guides,
    seqvizZoom, setSeqvizZoom, onFastaFileUpload
  ]);
}